# **Atividade 02 (ATIV-02)**
- Algoritmos básicos de programação em linguagem python e
análise de dados.

1. Escreva uma função que receba uma lista de números e retorne outra lista
com os números ímpares.

In [1]:
def impares(lista: list) -> list:
    impar = []
    for i in lista:
        if i % 2 == 0:
            continue
        else:
            impar.append(i)
    return impar

In [2]:
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(impares(lista=numeros))

[1, 3, 5, 7, 9]

2. Escreva uma função que receba uma lista de números e retorne outra lista
com os números primos presentes.

In [3]:
def filtrar_primos(lista_numeros):
    primos_encontrados = []

    for numero in lista_numeros:

        eh_primo = True

        if numero <= 1:
            eh_primo = False
        elif numero == 2:
            eh_primo = True
        elif numero % 2 == 0:
            eh_primo = False
        else:
            limite = int(numero ** 0.5) + 1
            for i in range(3, limite, 2):
                if numero % i == 0:
                    eh_primo = False
                    break

        if eh_primo:
            primos_encontrados.append(numero)

    return primos_encontrados

minha_lista = [1, 2, 3, 4, 5, 10, 11, 15, 17, 20, 23, 97, 100]

resultado = filtrar_primos(minha_lista)
print(resultado)

[2, 3, 5, 11, 17, 23, 97]

3. Escreva uma função que receba duas listas e retorne outra lista com os
elementos que estão presentes em apenas uma das listas.

In [4]:
def elementos_exclusivos(lista1, lista2):
    set1 = set(lista1)
    set2 = set(lista2)
    resultado = list(set1 ^ set2)
    return resultado

l1 = [1, 2, 3, 4]
l2 = [3, 4, 5, 6]
print(f"Ex 3: {elementos_exclusivos(l1, l2)}")

Ex 3: [1, 2, 5, 6]

4. Dada uma lista de números inteiros, escreva uma função para encontrar o
segundo maior valor na lista.

In [5]:
def segundo_maior(lista):
    lista_unica = sorted(list(set(lista)))

    if len(lista_unica) < 2:
        return None

    return lista_unica[-2]

numeros = [10, 20, 4, 45, 99, 99, 4]
print(f"Ex 4: {segundo_maior(numeros)}")

Ex 4: 45

5. Crie uma função que receba uma lista de tuplas, cada uma contendo o
nome e a idade de uma pessoa, e retorne a lista ordenada pelo nome das
pessoas em ordem alfabética.

In [6]:
def ordenar_pessoas(lista_pessoas):
    return sorted(lista_pessoas, key=lambda x: x[0])

pessoas = [("João", 25), ("Ana", 30), ("Carlos", 22)]
print(f"Ex 5: {ordenar_pessoas(pessoas)}")

Ex 5: [('Ana', 30), ('Carlos', 22), ('João', 25)]

6. Como identificar e tratar outliers em uma coluna numérica usando desvio
padrão ou quartis?

In [7]:
import pandas as pd

# 1. Criando os dados (dicionário)
dados = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo', 'Fernanda', 'Gabriel'],
    'Salario': [2500, 3000, 2800, 15000, 3200, 2900, 3100],
    'Cargo': ['Júnior', 'Pleno', 'Júnior', 'CEO', 'Pleno', 'Júnior', 'Pleno']
}

# 2. Transformando em DataFrame
df = pd.DataFrame(dados)

df

       Nome  Salario   Cargo
0       Ana     2500  Júnior
1     Bruno     3000   Pleno
2    Carlos     2800  Júnior
3     Diana    15000     CEO
4   Eduardo     3200   Pleno
5  Fernanda     2900  Júnior
6   Gabriel     3100   Pleno

In [8]:
df.to_csv("salario.csv", index=False)

In [9]:
def tratar_outliers_iqr(df, coluna):
    Q1 = df[coluna].quantile(0.25)
    Q3 = df[coluna].quantile(0.75)
    IQR = Q3 - Q1

    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    df_limpo = df[(df[coluna] >= limite_inferior) & (df[coluna] <= limite_superior)]
    return df_limpo


df_sem_outliers = tratar_outliers_iqr(df, 'Salario')

In [10]:
df_sem_outliers

       Nome  Salario   Cargo
0       Ana     2500  Júnior
1     Bruno     3000   Pleno
2    Carlos     2800  Júnior
4   Eduardo     3200   Pleno
5  Fernanda     2900  Júnior
6   Gabriel     3100   Pleno

7. Como concatenar vários DataFrames (empilhando linhas ou colunas),
mesmo que tenham colunas diferentes?
Dica: Utiliza-se pd.concat() especificando axis=0 (linhas) ou axis=1
(colunas). Quando há colunas diferentes, os valores ausentes são
preenchidos com NaN.

In [11]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'C': [7, 8]})

df_concat = pd.concat([df1, df2], axis=0, ignore_index=True)

df_concat

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0

8. Utilizando pandas, como realizar a leitura de um arquivo CSV em um
DataFrame e exibir as primeiras linhas?

In [12]:
df = pd.read_csv('salario.csv')

df.head()

      Nome  Salario   Cargo
0      Ana     2500  Júnior
1    Bruno     3000   Pleno
2   Carlos     2800  Júnior
3    Diana    15000     CEO
4  Eduardo     3200   Pleno

9. Utilizando pandas, como selecionar uma coluna específica e filtrar linhas
em um “DataFrame” com base em uma condição?

In [13]:
df = pd.DataFrame({'Produto': ['A', 'B', 'C'], 'Preco': [50, 150, 200]})

filtro = df[df['Preco'] > 100]

resultado = df.loc[df['Preco'] > 100, 'Produto']

filtro

  Produto  Preco
1       B    150
2       C    200

10.Utilizando pandas, como lidar com valores ausentes (NaN) em um
DataFrame?

In [14]:
import numpy as np
df = pd.DataFrame({'A': [1, 2, np.nan], 'B': [4, np.nan, 6]})

df_limpo = df.dropna()

df_preenchido = df.fillna(0)

df_preenchido

     A    B
0  1.0  4.0
1  2.0  0.0
2  0.0  6.0